DROP TABLE "Address";
DROP TABLE "ProductOrderQuantity";
DROP TABLE "Photo";
DROP TABLE "Product";
DROP TABLE "Category";
DROP TABLE "Employee";
DROP TABLE "Payment";
DROP TABLE "Order";
DROP TABLE "Customer";